国药项目/JFine.Web/Areas/Supplier/Controllers/SupplierBaseController.cs
//------------------------------------------------------------------------------
//     此代码由T4模板自动生成
//	   生成时间 2018-03-06 11:18:35
//    ©为之团队
//------------------------------------------------------------------------------

using JFine.Common.UI;
using JFine.Common.Json;
using JFine.Domain.Models.Supplier;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using JFine.Busines.Supplier;
using JFine.Web.Base.MVC.Handler;

namespace JFine.Web.Areas.Supplier.Controllers
{
    /// <summary>
    /// SupplierBaseController
    /// </summary>	
    public class SupplierBaseController : JFControllerBase
    {
        private SupplierBaseBLL supplierBaseBll = new SupplierBaseBLL();

        #region View
        //
        // GET: /Supplier/
        [HttpGet]
        [HandlerAuthorize]
        public override ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Form表单
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [HandlerAuthorize]
        public override ActionResult Form()
        {
            ViewBag.Id = Request["keyValue"];
            string operation = Request["operation"] ?? "";
            ViewBag.operation = operation;
            if (operation == "add") 
            {
                SupplierBaseEntity supplierBaseEntity = new SupplierBaseEntity();
                supplierBaseBll.SaveForm("", supplierBaseEntity);
                ViewBag.Id = supplierBaseEntity.Id;
            }
            return View();
        }
        
        /// <summary>
        /// Details表单
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [HandlerAuthorize]
        public override ActionResult Details()
        {
            var keyValue = Request["keyValue"] ?? "";
            ViewBag.keyValue = keyValue;
            return View();
        }

        [HttpGet]
        [HandlerAuthorize]
        public ActionResult Details2()
        {
            var keyValue = Request["keyValue"] ?? "";
            ViewBag.keyValue = keyValue;
            return View();
        }
        
        [HttpGet]
        [HandlerAuthorize]
        public ActionResult ApprovalIndex()
        {
            return View();
        }
        
        [HttpGet]
        [HandlerAuthorize]
        public ActionResult ApprovalForm()
        {
            var keyValue = Request["keyValue"] ?? "";
            ViewBag.keyValue = keyValue;
            return View();
        }
        
        [HttpGet]
        [HandlerAuthorize]
        public ActionResult ChooseSupplier()
        {
            return View();
        }
        
        /// <summary>
        /// 供应商资源库
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [HandlerAuthorize]
        public ActionResult ValidIndex()
        {
            return View();
        }

        #endregion

        #region 获取数据

        /// <summary>
        /// 列表 
        /// </summary>
        /// <param name="pagination">分页</param>
        /// <returns></returns>
        [HttpGet]
        [HandlerAjaxOnly]
        public ActionResult GetGridJson(Pagination pagination, string queryJson,int flag = 0)
        {
            var data = new
            {
                rows = supplierBaseBll.GetPageListBySql(pagination, queryJson, flag),
                total = pagination.total,
                page = pagination.page,
                records = pagination.records
            };
            return Content(data.ToJson());
        }

        /// <summary>
        /// 功能实体 返回对象Json
        /// </summary>
        /// <param name="keyValue">主键值</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetFormJson(string keyValue)
        {
            var data = supplierBaseBll.GetForm(keyValue);
            return Content(data.ToJson());
        }
        /// <summary>
        /// 功能实体 返回对象Json
        /// </summary>
        /// <param name="keyValue">主键值</param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult GetFormExtJson(string keyValue,string supno = "")
        {
            string queryJson = "";
            if (!string.IsNullOrWhiteSpace(supno))
            {
                queryJson = "{Id:\"" + keyValue + "\",SupNo:\"" + supno + "\",Status:\"通过\"}";
            }
            else 
            {
                queryJson = "{Id:\"" + keyValue + "\"}";
            }

            var data = supplierBaseBll.GetExtForm(queryJson);
            return Content(data.ToJson());
            
        }
        #endregion

        #region 提交数据
        /// <summary>
        /// 删除功能
        /// </summary>
        /// <param name="keyValue">主键值</param>
        /// <returns></returns>
        [HttpPost]
        [HandlerAjaxOnly]
        [HandlerAuthorize]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteForm(string keyValue)
        {
            supplierBaseBll.DeleteForm(keyValue);
            return Success("删除成功。");
        }

        /// <summary>
        /// 保存功能表单
        /// </summary>
        /// <param name="keyValue">主键值</param>
        /// <param name="SupplierBaseEntity">功能实体</param>
        /// <returns></returns>
        [HttpPost]
        [HandlerAjaxOnly]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult SaveForm(string keyValue, SupplierBaseEntity supplierBaseEntity, SupplierLinkmanEntity supplierLinkmanEntity)
        {
            string LinkManId = (Request["LinkManId"] ?? "").Trim();
            supplierLinkmanEntity.Id = LinkManId;
            supplierLinkmanEntity.BindId = keyValue;
            supplierBaseBll.SaveForm(keyValue, supplierBaseEntity, supplierLinkmanEntity);
            return Success("保存成功。");
        }
        /// <summary>
        /// 保存功能表单
        /// </summary>
        /// <param name="keyValue">主键值</param>
        /// <param name="SupplierBaseEntity">功能实体</param>
        /// <returns></returns>
        [HttpPost]
        [HandlerAjaxOnly]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult SaveForm2(string keyValue, SupplierBaseEntity supplierBaseEntity, SupplierLinkmanEntity supplierLinkmanEntity, List<SupplierFilesEntity> filedata, List<SupplierPurchaseORGEntity> purchasedata)
        {
            string LinkManId = (Request["LinkManId"] ?? "").Trim();
            supplierLinkmanEntity.Id = LinkManId;
            supplierLinkmanEntity.BindId = keyValue;
            supplierBaseBll.SaveForm(keyValue, supplierBaseEntity,supplierLinkmanEntity,filedata,purchasedata);
            return Success("保存成功。");
        }


        /// <summary>
        /// 保存功能表单
        /// </summary>
        /// <param name="keyValue">主键值</param>
        /// <param name="SupplierBaseEntity">功能实体</param>
        /// <returns></returns>
        [HttpPost]
        [HandlerAjaxOnly]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult SaveApprovalForm(string keyValue, SupplierBaseEntity supplierBaseEntity)
        {
            supplierBaseBll.SaveApprovalForm(keyValue, supplierBaseEntity);
            return Success("保存成功。");
        }

        #endregion

        #region 数据验证

        #endregion
    }
}

国药项目/JFine.Web/Areas/Supplier/Views/SupplierBase/ApprovalForm.cshtml
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Form2.cshtml";
}
<script>
    var origin = $.request("from");
    var keyValue = $.request("keyValue");
    $(function () {
        initControl();
        if (!!keyValue) {
            $.ajax({
                url: "/Supplier/SupplierBase/GetFormExtJson",
                data: { keyValue: keyValue },
                dataType: "json",
                async: false,
                success: function (data) {
                    $("#Id").val(data.Id);
                    $("#BINDID").val(data.BINDID);
                }
            });
        }
    });

    //初始化组件
    function initControl() {
        //审批结果
        $("#Status").bindSelect();
        $(".collapse-link").click(function () {
            var o = $(this).closest("div.ibox"),
                e = $(this).find("i"),
                i = o.find("div.ibox-content");
            i.slideToggle();
            e.toggleClass("fa-chevron-up").toggleClass("fa-chevron-down");
            o.toggleClass("").toggleClass("border-bottom");
        });
    }

    function submitForm() {
        if (!$('#form1').formValid()) {
            return false;
        }
        var postData = $("#form1").formSerialize();
        $.submitForm({
            url: "/Supplier/SupplierBase/SaveApprovalForm?keyValue=" + keyValue,
            param: postData,
            success: function () {
                var parentTabId = top.$.jfinetab.getCurrentTabParentId();
                var resultPage = top.$.jfinetab.getTabContentFromId(parentTabId);
                if (origin == "sy") {
                    resultPage.getProject();
                } else
                {
                    resultPage.refreshUnApproval();
                    resultPage.refreshApproval();
                }

                top.$.jfinetab.closeCurrentTab();
            }
        })
    }
	//关闭Form
    function closeForm() {
        top.$.jfinetab.closeCurrentTab();
    }
</script>

<form id="form1">
    <input type="hidden" id="Id" name="Id" value="" />
    <input type="hidden" id="BINDID" name="BINDID" value="" />
    <div id="jfine-form-container" class="jfine-form-container" border="0">
        <table id="jfine-form-maintable" class="jfineui jfine-form-maintable" style="table-layout: fixed;"
               border="0" cellspacing="0" cellpadding="0" align="center">
            <tbody>
                <tr id="jfine-form-titlebg" class="jfine-form-titlebg">
                    <td>
                        <table align="center" border="0" style="margin: 0px auto; width: 100%;">
                            <tbody>
                                <tr>
                                    <td class="jfine-form-header_l">
                                        <span class="jfine-form-logo">
                                            <img src="/Content/images/formlogo.png" />
                                        </span>
                                    </td>
                                    <td class="jfine-form-header_c">
                                        <span class="jfine-form-header-title">供应商审核</span>
                                    </td>
                                    <td class="jfine-form-header_r">
                                        <div>
                                            <div class="btn-group">
                                                <a class="btn btn-info dropdown-text" onclick="submitForm()"><i class="fa fa-send"></i>提交</a>
                                                <a class="btn btn-warning dropdown-text" onclick="closeForm()"><i class="fa fa-minus"></i>关闭</a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr id="jfine-form-formcontent" class="jfine-form-titlebg" style="">
                    <td>
                        <div style="margin-top: 10px; margin-left: 10px; margin-right: 10px;">
                            
                            <div class="ibox float-e-margins">
                                <div class="ibox-title">
                                    <h5 style="font-weight: bold;">审批信息</h5>
                                    <div class="ibox-tools">
                                        <a class="collapse-link">
                                            <i class="fa fa-chevron-up"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="ibox-content">
                                    <table class="form">
                                        <tr>
                                            <th class="formTitle"> 审批结果</th>
                                            <td class="formValue">
                                                <select id="Status" name="Status" class="form-control required">
                                                    <option value="通过">通过</option>
                                                    <option value="未通过">未通过</option>
                                                </select>
                                            </td>
                                            <th class="formTitle"> </th>
                                            <td class="formValue"></td>

                                        </tr>

                                        <tr>
                                            <th class="formTitle"> 审批意见</th>
                                            <td class="formValue" colspan="3">
                                                <textarea id="ApprovalSpec" name="ApprovalSpec" rows="4" class="form-control required" placeholder="请输入审批意见"></textarea>
                                            </td>
                                        </tr>

                                    </table>
                                </div>
                            </div>
                            
                            <div class="ibox float-e-margins">
                                <div class="ibox-title">
                                    <h5 style="font-weight: bold;">供应商信息</h5>
                                    <div class="ibox-tools">
                                        <a class="collapse-link">
                                            <i class="fa fa-chevron-up"></i>
                                        </a>
                                    </div>
                                </div>
                                <div id="project_div" class="ibox-content">
                                    @Html.Action("Details", "SupplierBase", new { keyValue = @ViewBag.keyValue })
                                </div>
                            </div>

                            

                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</form>

国药项目/JFine.Web/Areas/Supplier/Views/SupplierBase/ApprovalIndex.cshtml
@*------------------------------------------------------------------------------
    *     此代码由T4模板自动生成
    *	   生成时间 2017-12-21 10:19:32
    *     ©为之团队
    *------------------------------------------------------------------------------*@

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Index.cshtml";
}
<script>
    $(function () {
        gridList();
        gridList_ed();
    })
    //待审核列表
    function gridList() {
        var queryJson = {
            Status: "待审核"
        }
        var $gridList = $("#gridList");
        $gridList.dataGrid({
            url: "/Supplier/SupplierBase/GetGridJson",
            height: $(window).height() - 138,
            postData: { queryJson: JSON.stringify(queryJson) },
            colModel: [

					{ label: "主键", name: "Id", width: 150, align: 'left', hidden: true },

					{ label: "BindId", name: "BindId", width: 150, align: 'left', hidden: true },

					{ label: "状态 ", name: "Status", width: 60, align: 'left' },

                    { label: "供应商编码 ", name: "SupNo", width: 100, align: 'left' },

					{ label: "公司名称", name: "SupName", width: 150, align: 'left' },

					{ label: "企业性质", name: "Property", width: 100, align: 'left' },

					{ label: "采购类别", name: "PurchaseCategory", width: 100, align: 'left' },

                    { label: "联系人", name: "Name", width: 120, align: 'left' },

                    { label: '手机', name: 'Mobile', width: 150, align: 'left' },

                    { label: '电话', name: 'Phone', width: 100, align: 'left' },

                    { label: '邮箱', name: 'Email', width: 150, align: 'left' },

					{ label: " 创建日期", name: "CreateDate", width: 150, align: 'left' }


            ],
            pager: "#gridPager",
            sortname: 'CreateDate desc',
            viewrecords: true
        });
        $gridList.setGridWidth($(window).width() - 8);
        $("#btn_search").click(function () {
            var queryJson = {
                Status: "待审核",
                keyword: $("#txt_keyword").val()
            }
            $gridList.jqGrid('setGridParam', {
                postData: { queryJson: JSON.stringify(queryJson) }, page: 1
            }).trigger('reloadGrid');
        });
    }

    //已审核列表
    function gridList_ed() {
        var queryJson = {
            Status: "已审核"
        }
        var $gridList_ed = $("#gridList_ed");
        $gridList_ed.dataGrid({
            url: "/Supplier/SupplierBase/GetGridJson",
            height: $(window).height() - 138,
            postData: { queryJson: JSON.stringify(queryJson) },
            colModel: [

					{ label: "主键", name: "Id", width: 150, align: 'left', hidden: true },

					{ label: "BindId", name: "BindId", width: 150, align: 'left', hidden: true },

					{ label: "状态 ", name: "Status", width: 60, align: 'left' },

                    { label: "供应商编码 ", name: "SupNo", width: 100, align: 'left' },

					{ label: "公司名称", name: "SupName", width: 150, align: 'left' },

					{ label: "企业性质", name: "Property", width: 100, align: 'left' },

					{ label: "采购类别", name: "PurchaseCategory", width: 100, align: 'left' },

                    { label: "联系人", name: "Name", width: 120, align: 'left' },

                    { label: '手机', name: 'Mobile', width: 150, align: 'left' },

                    { label: '电话', name: 'Phone', width: 100, align: 'left' },

                    { label: '邮箱', name: 'Email', width: 150, align: 'left' },

					{ label: " 创建日期", name: "CreateDate", width: 150, align: 'left' }


            ],
            pager: "#gridPager_ed",
            sortname: 'CreateDate desc',
            viewrecords: true
        });
        $gridList_ed.setGridWidth($(window).width() - 8);
        $("#btn_search_ed").click(function () {
            var queryJson = {
                Status: "已审核",
                keyword: $("#txt_keyword_ed").val()
            }
            $gridList_ed.jqGrid('setGridParam', {
                postData: { queryJson: JSON.stringify(queryJson) }, page: 1
            }).trigger('reloadGrid');
        });
    }

    function btn_approval() {
        var keyValue = $("#gridList").jqGridRowValue().Id;
        if ($.checkedArray(keyValue)) {
            if ($("#gridList").jqGridRowValue().Status == "待审核") {
                var parentId = top.$.jfinetab.getCurrentTabId();
                top.$.jfinetab.addTabContent("/Supplier/SupplierBase/ApprovalForm?keyValue=" + keyValue , "供应商审核", parentId + "_approval", parentId);
            } else {
                $.modalAlert("只能选择《待审核》状态的数据！", "warning");
            }
        }

    }

    function btn_details() {
        var keyValue = $("#gridList").jqGridRowValue().Id;
        if ($.checkedArray(keyValue)) {
            var parentId = top.$.jfinetab.getCurrentTabId();
            top.$.jfinetab.addTabContent("/Supplier/SupplierBase/Details2?keyValue=" + keyValue, "供应商--详情", parentId + "_details", parentId);
        }
    }

    function btn_details_ed() {
        var keyValue = $("#gridList_ed").jqGridRowValue().Id;
        if ($.checkedArray(keyValue)) {
            var parentId = top.$.jfinetab.getCurrentTabId();
            top.$.jfinetab.addTabContent("/Supplier/SupplierBase/Details2?keyValue=" + keyValue, "供应商--详情", parentId + "_details", parentId);
        }
    }

    function refreshUnApproval() {
        var queryJson = {
            Status: "待审核"
        }
        $("#gridList").jqGrid('setGridParam', {
            postData: { queryJson: JSON.stringify(queryJson) }, page: 1
        }).trigger('reloadGrid');
    }

    function refreshApproval() {
        var queryJson = {
            Status: "已审核"
        }
        $("#gridList_ed").jqGrid('setGridParam', {
            postData: { queryJson: JSON.stringify(queryJson) }, page: 1
        }).trigger('reloadGrid');
    }
</script>

<div style="margin-top: 2px; margin-left: 2px; margin-right: 2px;">

    <div>
        <ul class="nav nav-tabs">
            <li role="presentation" class="active"><a href="#tab_unapproval" data-toggle="tab">待审批</a></li>
            <li role="presentation"><a href="#tab_approval" data-toggle="tab">已审批</a></li>
        </ul>
        <div class="tab-content">

            <!-- 待审批列表 -->
            <div class="tab-pane fade in active" id="tab_unapproval">
                <!-- 查询区域 -->
                <div class="topPanel">
                    <div class="toolbar">
                        <div class="btn-group">
                            <a class="btn btn-primary" onclick="refreshUnApproval()"><span class="glyphicon glyphicon-refresh"></span></a>
                        </div>
                        <div class="btn-group">
                            <a id="JF-add" class="btn btn-primary dropdown-text" onclick="btn_approval()"><i class="fa fa-plus"></i>审核</a>
                            <a id="JF-Details" class="btn btn-primary dropdown-text" onclick="btn_details()"><i class="fa fa-search-plus"></i>查看</a>
                        </div>
                        <div id="toolbar" class="btn-group">
                        </div>
                    </div>
                    <div class="search">
                        <table>
                            <tr>
                                <td>
                                    <div class="input-group">
                                        <input id="txt_keyword" type="text" class="form-control" placeholder="名称/编号" style="width: 200px;">
                                        <span class="input-group-btn">
                                            <button id="btn_search" type="button" class="btn  btn-primary"><i class="fa fa-search"></i></button>
                                        </span>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="gridPanel">
                    <table id="gridList"></table>
                    <div id="gridPager"></div>
                </div>
            </div>

            <!-- 已审批列表 -->
            <div class="tab-pane fade" id="tab_approval">
                <!-- 查询区域 -->
                <div class="topPanel">
                    <div class="toolbar">
                        <div class="btn-group">
                            <a class="btn btn-primary" onclick="refreshApproval()"><span class="glyphicon glyphicon-refresh"></span></a>
                        </div>
                        <div class="btn-group">
                            <a id="JF-Details" class="btn btn-primary dropdown-text" onclick="btn_details_ed()"><i class="fa fa-search-plus"></i>查看</a>
                        </div>
                        <div id="toolbar" class="btn-group">
                        </div>
                    </div>
                    <div class="search">
                        <table>
                            <tr>
                                <td>
                                    <div class="input-group">
                                        <input id="txt_keyword_ed" type="text" class="form-control" placeholder="名称/编号" style="width: 200px;">
                                        <span class="input-group-btn">
                                            <button id="btn_search_ed" type="button" class="btn  btn-primary"><i class="fa fa-search"></i></button>
                                        </span>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
                <div class="gridPanel">
                    <table id="gridList_ed"></table>
                    <div id="gridPager_ed"></div>
                </div>
            </div>

        </div>
    </div>
</div>

国药项目/JFine.Web/Areas/Supplier/Views/SupplierBase/ChooseSupplier.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Index.cshtml";
}
<script>
    var keyValue = $.request("keyValue");
    var Category = $.request("Category");//采购类别
    var windowId = $.request("windowId");//window ID
    var isSingle = $.request("isSingle");//是否单选：1:是；非1：否
    $(function () {
        gridList();
    })
    function gridList() {
        var queryJson = {
            keyword: $("#txt_keyword").val(),
            vstatus: 1,
            Category: Category,
            isOrg:1
        }
        var $gridList = $("#gridList");
        $gridList.dataGrid({
            url: "/Supplier/SupplierBase/GetGridJson?flag=1",
            height: $(window).height() - 138,
            postData: { queryJson: JSON.stringify(queryJson) },
            multiselect: true,
            colModel: [

                    { label: "供应商编码 ", name: "SupNo", width: 100, align: 'left' },

					{ label: "公司名称", name: "SupName", width: 150, align: 'left' },

                    { label: "联系人", name: "Name", width: 120, align: 'left' },

                    { label: '手机', name: 'Mobile', width: 150, align: 'left' },

                    { label: '电话', name: 'Phone', width: 100, align: 'left' },

                    { label: '邮箱', name: 'Email', width: 150, align: 'left' },

                    { name: 'Area', label: '省', width: '100', hidden: true },

                    { name: 'Area1', label: '市', width: '100', hidden: true },

                    { name: 'Area2', label: '区县', width: '100', hidden: true },

                    { name: 'Area3', label: '街道', width: '100', hidden: true }

            ],
			pager: "#gridPager",
            sortname: 'CreateDate desc',
            viewrecords: true
        });
        $("#btn_search").click(function () {
			var queryJson = {
			    keyword: $("#txt_keyword").val(),
			    vstatus: 1,
			    Category: Category,
			    isOrg: 1
            }
		    $gridList.jqGrid('setGridParam', {
		         postData: { queryJson: JSON.stringify(queryJson) }, page: 1
		    }).trigger('reloadGrid');
        });
    }

    //选择供应商--确定
    function chooseSupConfirm() {

        var list = $("#gridList").jqGridRows();
        if (list.length > 0) {
            if (windowId == '') {
                $.currentWindow().dealSelectedSup(list);
            } else {
                top.frames[windowId].dealSelectedSup(list);
            }
            $.modalClose();
        }
        else {
            $.modalAlert("请选择需要添加的数据", "warning");
        }
    }

    function refreshGrid() {
        $("#gridList").trigger("reloadGrid");
    }
</script>

<div class="topPanel">
    <div class="search">
        <table>
            <tr>
                <td>
                    <div class="input-group">
                        <input id="txt_keyword" type="text" class="form-control" placeholder="名称/编号" style="width: 200px;">
                        <span class="input-group-btn">
                            <button id="btn_search" type="button" class="btn  btn-primary"><i class="fa fa-search"></i></button>
                        </span>
                    </div>
                </td>
            </tr>
        </table>
    </div>
</div>
<div class="gridPanel">
    <table id="gridList"></table>
    <div id="gridPager"></div>
</div>